realizar_pesquisa:
  description: >
    Faça uma pesquisa simples sobre o tema usando DuckDuckGo.
    Foque apenas nos pontos principais, evitando detalhes técnicos ou históricos extensos.

  expected_output: >
    Um resumo direto com no máximo 2 tópicos curtos, com dados atualizados.

  agent: pesquisador

sintetizar_informacoes:
  description: >
    Resuma as informações do pesquisador de forma clara e direta.
    Elimine repetições e foque nos pontos-chave mais relevantes, identifique o tema também.

    **Tema:**
    {tema}
    
  expected_output: >
    Um resumo curto e objetivo mostrando o tema e com no máximo 2 linhas, destacando apenas os pontos essenciais.
    O texto deve ser fácil de entender e cobrir o tema de forma geral, sem detalhes técnicos.

  agent: sintetizador

pesquisa_wikipedia_task:
  description: >
    Busque na Wikipedia apenas as informações essenciais sobre: {tema}
    Use o parâmetro max_chars=1500 para limitar o tamanho do resultado.

  expected_output: >
    Resumo conciso das informações principais (máximo 1500 caracteres)

  agent: wikipedia_pesquisador

escrever_artigo_task:
  description: >
    Escreva um artigo de exatamente 300 palavras sobre "{tema}" usando 
    as informações fornecidas. Estruture com introdução, desenvolvimento e conclusão.

  expected_output: >
    Um artigo de exatamente 300 palavras, bem estruturado e informativo.

  agent: redator_artigo
